BackBundle\Entity\Page:
    type: entity
    table: null
    gedmo:
        translation:
          locale: locale
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        alias:
            type: string
            length: 255
        title:
            type: string
            length: 255
            gedmo:
                - translatable
        text:
            type: text
            gedmo:
                - translatable
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
        active:
            type: boolean
            nullable : true
        archive:
            type: boolean
            nullable : true

    lifecycleCallbacks: {  }
